# Generated by Django 2.1.5 on 2019-01-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('server_name', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=80)),
                ('cmd', models.CharField(max_length=255)),
                ('host_date', models.DateTimeField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StatusInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=80)),
                ('status', models.CharField(max_length=255)),
                ('status_date', models.DateTimeField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
